// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryphwhchdbkktbdoevga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5cGh3aGNoZGJra3RiZG9ldmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwMTA3NTAsImV4cCI6MjA5MDU4Njc1MH0.V7U9ZdT0Nqmjovq4So6T3JhyIPJhaqnQghOW7Bc0g3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});